name: "terraform destroy"
on: workflow_dispatch

jobs:
  issue_parser:
    runs-on: ubuntu-latest
    name: Terraform destroy
    steps:
      - name: Terraform destroy
        uses: daniyalj/terraform-destroy-actions@v3
        with:
          org_name: 'code_test'
          repo_name: 'code_test'