name: 'Terraform CI/CD Pipeline'
on:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: ${{ github.action == 'terraform-automation' }}
  cancel-in-progress: true

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -recursive
      continue-on-error: true

    - name: Terraform Plan
      run: terraform plan -out=plan.out && terraform show -json plan.out > plan.out.json

    - name: terraform-compliance
      uses: terraform-compliance/github_action@main
      run: terraform-compliance -p ./plan.out.json -f ../test/test.features

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve

    - name: Terraform Outputs
      run: terraform output instance_id && terraform output key_pairs_map